apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      name: front
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: 324105357214.dkr.ecr.ap-northeast-2.amazonaws.com/front:latest
